### PR TITLE
Ensemble

### PR DESCRIPTION
**Pull request by petered**

### CODE REVIEW

**Comment by petered** [comment]
Passed Tests

**Comment by petered** [comment]
passed tests

**Comment by petered** [comment]
I'm not reviewing all that!

**Comment by petered** [comment]
Yes you are

**Comment by petered** [comment]
It's good enough.

**Comment by y0ast** [comment]
Having fun? :smile:

**Comment by petered** [comment]
We are always having fun.

**Comment by petered** [comment]
Shut up!  Just shut up!  Nothing about this is fun.

**Pull request merged**
